### ISSUE TITLE
haco fails to install

### ISSUE THREAD

**Issue by RSABear** [fmtr/haco#2]
haco version 0.0.20
Home Assistant
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

Steps to re-create. Followed the instructions on README/Home Assistant install.
Added the haco add-on, and it appears in the Add-on Store.

When I click on install the following Error message appears:
Failed to install add-on: The command '/bin/ash -o pipefail -c pip install haco==${BUILD_VERSION}' returned a non-zero code: 1

![Capture_1](https://github.com/fmtr/haco/assets/11326160/65f30525-8bcd-40c9-91e5-a4f660e871be)
![Capture_2](https://github.com/fmtr/haco/assets/11326160/c7cbe4e2-314c-4522-abc4-676915130c71)

**Comment by deltaroe** [comment]
Think this should solve this https://github.com/fmtr/haco/pull/3

**Comment by RSABear** [comment]
It worked. The steps were. Install pipx, I followed the Linux commands. Install the haco 0.0.20 package. Inject the dependency.
Without your help I would have never achieved it. Let me proceed with the Berry scripting.

**Comment by RSABear** [comment]
done. 
Just want to add the edits here. (I re-loaded my test PI and needed to re-install the add-on and had to remember what I did to get it running)

Do a local Add-on install. Create \haco directory in \config. Copy DockerFile, run.sh and config.yaml 


Edit DockerFile.

ARG BUILD_FROM
FROM $BUILD_FROM
ARG BUILD_VERSION

RUN apk add --no-cache pipx
ENV PATH="${PATH}:/root/.local/bin"
RUN pipx install haco==${BUILD_VERSION}
RUN pipx inject haco aiomqtt==1.2.1

COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]


Edit run.sh

#!/usr/bin/with-contenv bashio

export HACO_IS_ADDON=true
export HACO_CONFIGS_PATH="/config/haco"
export HACO_OPTIONS_PATH="/data/options.json"
export MQTT_HOST="$(bashio::services mqtt 'host')"
export MQTT_PASSWORD="$(bashio::services mqtt 'password')"
export MQTT_PORT="$(bashio::services mqtt 'port')"
export MQTT_USERNAME="$(bashio::services mqtt 'username')"

haco-daemon


Check log file, config directory will be created. Edit the configuration in the add-on. Restart.
Reload your Berry config requirements.

**Comment by ejohb** [comment]
I've released a more principled fix (until I can properly account for `aiomqtt==2.0` at least) - but since I'm not currently running supervised, I cannot check that. Give the latest a try and let me know if you have any issues.
